### ISSUE TITLE
1Hz rate group component declaration missing

### ISSUE THREAD

**Issue by nathancheek** [SterlingPeet/cookiecutter-fprime-deployment#4]
The `rateGroup1HzComp` is referenced in commented out lines in the `TopologyAi.xml` as well as `Topology.cpp` files, but not in `Components.hpp`. As it is now, the user must uncomment lines in `TopologyAi.xml`, `Topology.cpp`, and `SchedContexts.hpp`, then add a line to `Components.hpp` to set up the 1Hz rate group.

`Components.hpp` should be set up like the other files so the user can easily set up a 1Hz rate group by just uncommenting the right lines in the 4 related boilerplate files.

`// extern Svc::ActiveRateGroupImpl rateGroup1HzComp;` should be added here: https://github.com/SterlingPeet/cookiecutter-fprime-deployment/blob/572ebe684829dec6481c3fefcca8e49f143fa5c8/%7B%7Bcookiecutter.deployment_dir_name%7D%7D/Top/Components.hpp#L21

**Comment by SterlingPeet** [comment]
Good catch, maybe I should just add this rate group as a cookiecutter option.  Basically, if you answer ``yes`` the relevant lines are all uncommented, and if you answer ``no`` they are all still there, but commented out.

**Comment by SterlingPeet** [comment]
Well, I have added the commented out line, although it is not yet pushed.  I think I will actually leave it that way for now, and make additional example rate groups an option in a later update (when it generates something more complete, like ``Ref``).
